name: 'Merge branches with production code'

on:
  push:
    branches:
      - master

jobs:
  demo-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Demo Merge
        uses: robotology/gh-action-nightly-merge@v1.2.0
        with:
          stable_branch: 'master'
          development_branch: 'demo'
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  globe-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Globe Merge
        uses: robotology/gh-action-nightly-merge@v1.2.0
        with:
          stable_branch: 'master'
          development_branch: 'globe'
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  main-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Globe Merge
        uses: robotology/gh-action-nightly-merge@v1.2.0
        with:
          stable_branch: 'master'
          development_branch: 'main'
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
